language: python
sudo: required
dist: trusty
python:
  - "2.7"
env:
  matrix:
    - LIBRDKAFKA_VERSION=v0.9.4
    - LIBRDKAFKA_VERSION=v0.9.5
    - LIBRDKAFKA_VERSION=v0.11.0
before_install:
  - sudo bash tools/bootstrap-librdkafka.sh ${LIBRDKAFKA_VERSION} /usr/local
  - sudo ldconfig -vvv
  - pip install --upgrade pip
  - pip install -r requirements_dev.txt
install:
  - pip install -v .
script:
  - flake8 syslogng_kafka tests
  - py.test -v --timeout 20 --import-mode append
