# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

sudo: false

language: python

# It is currently necessary to specify python 3.5 when using py35 on Travis,
# see https://github.com/travis-ci/travis-ci/issues/4794
matrix:
  include:
    - python: 3.5
      env:
        - TOX_ENV=py35
    - python: 3.4
      env:
        - TOX_ENV=py34
    - python: 3.3
      env:
        - TOX_ENV=py33
    - python: 2.7
      env:
        - TOX_ENV=py27
    - python: 3.5
      env:
        - TOX_ENV=docs
    - python: 3.5
      env:
        - TOX_ENV=flake8

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox

# command to run tests, e.g. python setup.py test
script: tox -e $TOX_ENV
